import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import ResponsiveNav from "../../components/Home/Navbar/ResponsiveNav";

const font = Sora({
  weight:['100','200','300','400','500','600','700','800'],
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create portfolio website",
  description: "Generated by using next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className}  antialiased bg-[white] text-[black] dark:bg-[#050709] dark:text-[#f1f5f9]`}
      >
        <ResponsiveNav/>
        {children}
      </body>
    </html>
  );
}
